# ==== Unlauncher ====
$UnlauncherBin = ~/.scripts/bin/unlauncher
bindn = , control_l, exec, sleep 0.2 && hyprctl dispatch submap reset
bindn = , control_l, submap, launcher
submap = launcher
bind = , control_l, exec, $UnlauncherBin
bind = , control_l, submap, reset
submap = reset

windowrule {
  name = unlauncher-window
  match:title = Unlauncher
  match:initial_title = Unlauncher
  
  center = true
  float = true
  size = 40% 30%
}
